# Generated by Django 3.2.16 on 2024-03-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20240326_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='future_post',
            field=models.BooleanField(default=False),
        ),
    ]
