# Generated by Django 3.2.16 on 2024-03-26 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20240326_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='future_post',
        ),
    ]
